[package]
name = "aetherment"
version = "0.1.4"
edition = "2021"

[dependencies]
renderer = {path = "../renderer"}
noumenon = {path = "../noumenon"}

serde = {version = "1.0.171", features = ["derive"]}
serde_json = "1.0.103"

rand = "0.8.5"
dirs = "5.0.1"
binrw = "0.11.2"
ureq = {version = "2.10.0", features = ["json"]}
tempfile = "3.10.1"

image = "0.24.2"
zip = {version = "0.6.6", features = ["deflate"]}
flate2 = "1.0.26"
blake3 = "1.3.1"
base32 = "0.5.0"
base64 = "0.22.1"

[features]
client = ["renderer/egui"]
plugin = ["renderer/imgui"]